### ISSUE TITLE
Fastapi & Python 3.9

### ISSUE THREAD

**Issue by studio-salamander** [ycd/manage-fastapi#30]
Hi!
Are there any discrepancies in the support for Python versions?

![image](https://user-images.githubusercontent.com/9484902/106916148-8779aa00-670f-11eb-8642-dc8197be728e.png)

Interested in support v3.9
Do I understand correctly that the help text about Python versions is just incomplete?

![image](https://user-images.githubusercontent.com/9484902/106920350-ad08b280-6713-11eb-9409-4ea10d0dcf22.png)

Thankx

**Comment by Kludex** [comment]
The Python 3.9 you see is from the CI i.e. it runs the test set against Python 3.9. 

But FastAPI is not supporting 3.9 officially... So, maybe we should remove 3.9 from the CI? :thinking: 
I don't see any issue on adding the 3.9 in the command as well...

**Comment by Kludex** [comment]
FastAPI now supports Python 3.9. jfyk

**Comment by studio-salamander** [comment]
@Kludex thank you very much for your answer ;)
