### ISSUE TITLE
[DOC][BUG] Static files are not generated properly in doc website

### ISSUE THREAD

**Issue by ShahriyarR** [ycd/manage-fastapi#33]
It seems to be the doc assets are missing:

![failing_assets](https://user-images.githubusercontent.com/3852029/118113923-f5f99280-b3f7-11eb-8efb-7c542779cb93.png)

Also the .md files are not converted to .HTML files:

![md_files_missing_htmls](https://user-images.githubusercontent.com/3852029/118114080-2b05e500-b3f8-11eb-9ffe-54432084972b.png)

**Comment by ycd** [comment]
Yeah, we had a github.io page back then, after refactor it became obsolete and i forgot to delete it, thanks for the report @ShahriyarR :)
