### ISSUE TITLE
[Help] I would like to ask for terminal and terminalizer settings

### ISSUE THREAD

**Issue by ShahriyarR** [ycd/manage-fastapi#56]
Hi dear all,
I would like to use your README style in one of the projects.
The needed thing for me is the terminal template name(I guess it is oh-my-bash but which template/font?)
Also if it is possible to share the terminalizer configs - for creating the gif file. I am struggling with getting proper resolution and style.
Thanks :)

**Comment by ycd** [comment]
Hey, the all settings that i use for my terminal and coloring can be found in my [dotfiles repository](https://github.com/ycd/dots). 

I use a simple ffmpeg command to create gif from screen record.

```zsh
ffmpeg -i ${INPUT_FILE_PATH} -filter_complex "fps=10,scale=850:-1:flags=lanczos[x];[x]split[x1][x2]; [x1]palettegen[p];[x2][p]paletteuse" -r 15 output.gif
```
