### ISSUE TITLE
Remove support of python 3.6

### ISSUE THREAD

**Issue by kaieslamiri** [ycd/manage-fastapi#96]
As long as the FastAPI version has been bumped to 0.85.0 and it also drops the support to the python version 3.6 as mentionned here : https://fastapi.tiangolo.com/release-notes/ , shouldn't we drop the support within the package (This will make it also possible to make some updates on the packages such as Black, pydantic, ...

**Comment by Kludex** [comment]
PR is welcome. 🙏

**Comment by Kludex** [comment]
Done :+1:
